(dp1
S'output'
p2
S"<type 'exceptions.SyntaxError'> Adapter not found for sqlite:storage"
p3
sS'layer'
p4
S'C:\\Users\\TOSHIBA\\Desktop\\School\\web2py\\web2py\\applications\\signup_form\\models\\db.py'
p5
sS'code'
p6
S'<code object <module> at 042D6EC0, file "C:\\Users\\TOSHIBA\\Desktop\\School\\web2py\\web2py\\applications\\signup_form\\models\\db.py", line 1>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Users\\TOSHIBA\\Desktop\\School\\web2py\\web2py\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "C:\\Users\\TOSHIBA\\Desktop\\School\\web2py\\web2py\\applications\\signup_form\\models\\db.py", line 4, in <module>\n    db = DAL("sqlite:storage.sqlite")\n  File "C:\\Users\\TOSHIBA\\Desktop\\School\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 170, in __call__\n    obj = super(MetaDAL, cls).__call__(*args, **kwargs)\n  File "C:\\Users\\TOSHIBA\\Desktop\\School\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 454, in __init__\n    adapter = adapters.get_for(self._dbname)\n  File "C:\\Users\\TOSHIBA\\Desktop\\School\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\__init__.py", line 20, in get_for\n    \'Adapter not found for %s\' % uri\nSyntaxError: Adapter not found for sqlite:storage\n'
p11
s.